export enum WaslResultCode {
  SUCCESS = 'success',
  BAD_REQUEST = 'bad_request',
  DRIVER_VEHICLE_DUPLICATE = 'DRIVER_VEHICLE_DUPLICATE',
  DRIVER_NOT_ALLOWED = 'DRIVER_NOT_ALLOWED',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',
  VEHICLE_NOT_OWNED_BY_FINANCIER = 'VEHICLE_NOT_OWNED_BY_FINANCIER',
  DRIVER_NOT_AUTHORIZED_TO_DRIVE_VEHICLE = 'DRIVER_NOT_AUTHORIZED_TO_DRIVE_VEHICLE',
  NO_VALID_OPERATION_CARD = 'NO_VALID_OPERATION_CARD',
  CONTACT_WASL_SUPPORT = 'CONTACT_WASL_SUPPORT',
  NO_OPERATIONAL_CARD_FOUND = 'NO operational Card found',
}

export enum waslRegistrationStatus {
  VALID = 'VALID',
  INVALID = 'INVALID',
  PENDING = 'PENDING',
  NOT_REGISTERED = 'NOT_REGISTERED',
}
