import { Router } from 'express';

import authRouter from './authRouter';
import cityRouter from './cityRouter';
import meetingLocationRouter from './meetingLocationRouter';
import promoCodeRouter from './promoCodeRouter';
import userRouter from './userRouter';
import hobbyRouter from './hobbyRouter';
import addressRouter from './addressRouter';
import complaintRouter from './complaintRouter';
import vehicleRouter from './vehicleRouter';
import issueRouter from './issueRouter';
import reasonRouter from './reasonRouter';
import basicRouter from './basicTripRouter';
import vipTripRouter from './vipTripRouter';
import driverRouter from './driverRouter';
import walletRouter from './walletRouter';
import vehicleDerailsRouter from './vehicleDetailsRouter';
import reviewRouter from './reviewRouter';
import recentAddressRouter from './recentAddressRouter';
import notificationRouter from './notificationRouter';
import favoriteDriverRouter from './favoriteDriverRouter';
import tripRouter from './tripRouter';
import adminDashboardRouter from './adminDashboardRouter';
import policyServiceRouter from './policyServiceRouter';
import chatRouter from './chatRouter';
import messageRouter from './messageRouter';
import paymentGatewayRouter from './paymentGatewayRouter';
import warningRouter from './warningRouter';
import settlementRequestRouter from './settlementRequestRouter';
import savedCardRouter from './savedCardRouter';
import driverReport from './driverReportRouter';
import offerRouter from './offerRouter';
import paymentStatus from './paymentStatus';
import pdfReportRouter from './pdfReportRouter';
import appConfigRouter from './appConfigRouter';
import waslRouter from './waslRouter';

const router = Router();

router.use('/auth', authRouter);
router.use('/city', cityRouter);
router.use('/meeting-location', meetingLocationRouter);
router.use('/promo-code', promoCodeRouter);
router.use('/user', userRouter);
router.use('/hobby', hobbyRouter);
router.use('/address', addressRouter);
router.use('/complaint', complaintRouter);
router.use('/vehicle', vehicleRouter);
router.use('/issue', issueRouter);
router.use('/reason', reasonRouter);
router.use('/basic-trip', basicRouter);
router.use('/reason', reasonRouter);
router.use('/vip-trip', vipTripRouter);
router.use('/driver', driverRouter);
router.use('/wallet', walletRouter);
router.use('/vehicle-details', vehicleDerailsRouter);
router.use('/review', reviewRouter);
router.use('/recent-address', recentAddressRouter);
router.use('/notification', notificationRouter);
router.use('/favorite-driver', favoriteDriverRouter);
router.use('/trip', tripRouter);
router.use('/admin-dashboard', adminDashboardRouter);
router.use('/policy-service', policyServiceRouter);
router.use('/chat', chatRouter);
router.use('/message', messageRouter);
router.use('/payment-getway', paymentGatewayRouter);
router.use('/warning', warningRouter);
router.use('/settlement-request', settlementRequestRouter);
router.use('/saved-card', savedCardRouter);
router.use('/driver-report', driverReport);
router.use('/offer', offerRouter);
router.use('/payment-status', paymentStatus);
router.use('/pdf-report', pdfReportRouter);
router.use('/app-config', appConfigRouter);
router.use('/wasl-integration', waslRouter);

export default router;
